---
# Linux 
linux_inventory_name: linux-devices
linux_lab_device_1: 192.168.1.100  # tough-guy
linux_lab_device_2: 192.168.1.101  # black-panther
linux_devices_group: linux

# AWS EC2
aws_ec2_inventory_name: aws-ec2-inventory
aws_ec2_inventory_source: aws-ec2-inventory-source
