---
# File containing network systems variables


# Design will look different if TACACS/RADIUS is involved and there's no fixed m-to-m account
# Why not use m-2-m account and use login name for audit trails?

# Linux Servers credentials
linux_aap_credential_name: linux-machine-credential
linux_aap_credential_type: Machine  
linux_user: "{{ lookup('env', 'LINUX_USER') }}"
linux_password: "{{ lookup('env', 'LINUX_PASSWORD') }}"

