---
# Contains variables that are fixed
# The dynamic.yml vars files picks changes from here and feeds them into the different modules.
# This is the only file you should edit.


# Authentication credentials set as env variables. Could be fixed variables in AAP.
# export TOWER_HOST=https://******
# export TOWER_USERNAME=***
# export TOWER_PASSWORD=***
# export TOWER_VERIFY_SSL=0

# Organization. Object at the top
organization_name: your-value

# Execution environment 
exec_env_name: "your-value"


# Credentials
devices_creds: "your-value"
docker_registry_creds: "your-value"    # Came in handy during dev and no access to PAH
smtp_email_creds: "your-value"
source_control_creds: "your-value" # In the dev environment, these are github credentials used
pah_registry_creds: "your-value" # Specific for the pah in Ausgrid


# Projects . These can be changing from time to time
project_name: your-value
project_scm_url: your-value # To be changed to Azure
project_scm_branch: main # Should always be dev!


# Inventory
inventory_name: "your-value"

# Container images
podman_image_name: "your-value"

# F5 Upgrade Phases
phase_1: "pre-change-checks"
phase_2: "config-backup"
phase_3: "monitoring"
phase_4: "execute-change"
phase_5: "post-change-checks"
phase_666: "fail-detour"

# Devices serving as hosts ( Not needed if using smart inventory or bigger inventory )
# Could be IP or resolvable FQDN
lab_device_1: your-value
lab_device_2: your-value