---
# Create job templates for Linux
# Enables unittesting by running one job at a time, before running workflow as end-to-end
- name: Create job templates
  ansible.controller.job_template:
    name: "job-{{ item }}"
    job_type: "run"
    description: "{{ aap_objects_build_repo }}"
    organization: "{{ organization_name }}"
    inventory: "{{ linux_inventory_name }}"
    project: "{{ linux_env_aap_project_name }}"
    playbook: "{{ item }}.yml"
    credentials: "{{ linux_aap_credential_name }}"
    state: "present"
    execution_environment: "{{ aap_exec_env_name }}"
    timeout: 60
  loop:
    - "{{ linux_env_phase_1 }}"
    - "{{ linux_env_phase_2 }}"
    - "{{ linux_env_phase_3 }}"
