---
# Docker hub
# - name: Create docker container hub credential
#   ansible.controller.credential:
#     name: "{{ docker_registry }}"
#     organization: "{{ organization_name }}"
#     state: present
#     credential_type: Container Registry
#     inputs:
#       username: "{{ docker_user }}"
#       password: "{{ docker_access_token }}"
#     validate_certs: false

- name: "Set variables for {{ container_registry_credential_name }}" 
  ansible.builtin.set_fact:
    credential_name: "{{ container_registry_credential_name }}"
    organization: "{{ organization_name }}"
    credential_type: "{{ container_registry_credential_type }}"
    username: "{{ container_registry_user }}"
    password: "{{ container_registry_password }}"

- name: Call build-credential module
  ansible.builtin.import_tasks: build-credential.yml