---
# Building credentials for use
# REF: https://docs.ansible.com/ansible/latest/collections/awx/awx/credential_module.html
# Usually the creds needed are:
# 1. Container registry - Execution environment.
# 2. Git Repo - Where all the playbooks/scripts are pulled from.
# 3. Machine-machine - Devices to be ssh(d) into(like Cisco, Juniper) or API Calls (like F5s)
# 4. Email - If notifications are to be sent as emails.

# - name: Create a Credentials objects in AAP
#   ansible.controller.credential:
#     name: "{{ item[0] }}"
#     organization: "{{ organization_name }}"
#     state: present
#     credential_type: "{{ item[1] }}"
#     inputs:
#       username: "{{ item[2] }}"
#       password: "{{ item[3] }}"
#     validate_certs: false
#   loop:
#     #- ["{{ smtp_email_creds }}",Insights, "{{ lookup('env', 'EMAIL_USER') }}" , "{{ lookup('env', 'EMAIL_PASSWORD') }}"] # Email credential
#     - ["{{ linux_servers }}", Machine, "{{ lookup('env', 'LINUX_USER') }}" , "{{ lookup('env', 'LINUX_PASSWORD') }}"] # Network credential
#     #- ["{{ source_control_creds }}", Source Control, "{{ lookup('env', 'GIT_USER') }}" , "{{ lookup('env', 'GIT_PASSWORD') }}"] # SCM credential
#     - ["{{ github_access }}", GitHub Personal Access Token, "{{ lookup('env', 'GITHUB_USER') }}" , "{{ lookup('env', 'GITHUB_PASSWORD') }}"] # Network credential
#     - ["{{ docker_access }}", Container Registry, "{{ lookup('env', 'DOCKER_USER') }}" , "{{ lookup('env', 'DOCKER_PASSWORD') }}"] # Docker credential

#     # What if TACACs/RADIUS is in use? Maybe a machine credential for automation? Or client needs audit trail of users? Then make it a prompt!


- name: Build machine credential
  ansible.builtin.import_tasks: machine.yml

- name: Build source-control credential
  ansible.builtin.import_tasks: source-control.yml

- name: Build container-hub credential
  ansible.builtin.import_tasks: container-registry.yml