---
# Intrestingly, GitHub/GitLab Personal Access Token takes in only Token.
# Is that all what's needed?

# - name: Create linux servers credential
#   ansible.controller.credential:
#     name: "{{ github }}"
#     organization: "{{ organization_name }}"
#     state: present
#     credential_type: Source Control
#     inputs:
#       username: "{{ github_user }}"
#       password: "{{ github_access_token }}"
#     validate_certs: false

- name: Set variables for vcs 
  ansible.builtin.set_fact:
    credential_name: "{{ vcs_aap_credential_name }}"
    organization: "{{ organization_name }}"
    credential_type: "{{ vcs_aap_credential_type }}"
    username: "{{ vcs_user }}"
    password: "{{ vcs_password }}"

- name: Call build-credential module
  ansible.builtin.import_tasks: build-credential.yml