---
# Reusable module


# https://docs.ansible.com/ansible/latest/collections/awx/awx/inventory_module.html
# NB! After this you will need to get into the inventory on GUI and populate it with hosts


## How do we build a smart inventory??

- name: "Create inventory = {{ inventory_name }}"
  ansible.controller.inventory:
    name: "{{ inventory_name }}"
    description: "{{ aap_objects_build_repo }}"
    organization: "{{ organization_name }}"
    state: present
    #controller_config_file: "~/tower_cli.cfg"