---
# Build the aws project

- name: "Create {{ aws_aap_project_name }} project"
  ansible.controller.project:
    name: "{{ aws_aap_project_name }}"
    description: "{{ aap_objects_build_repo }}"
    organization: "{{ organization_name }}"
    scm_type: "git"
    scm_url: "{{ aws_aap_project_scm_url }}"
    scm_branch: "{{ aws_aap_project_scm_branch }}"
    scm_credential: "{{ vcs_aap_credential_name }}"
    scm_update_on_launch: true     # Perform an update to the local repository before launching a job with this project.
    scm_update_cache_timeout: 60
    state: present
    #controller_config_file: "~/tower_cli.cfg"