---
# Reusable modules

# Build the Project as part 2 of the playbook
# REF: https://docs.ansible.com/ansible/latest/collections/awx/awx/project_module.html

- name: "Create {{ project_name }} project"
  ansible.controller.project:
    name: "{{ project_name }}"
    description: "{{ aap_objects_build_repo }}"
    organization: "{{ organization_name }}"
    scm_type: "git"
    scm_url: "{{ scm_url }}"
    scm_branch: "{{ scm_branch }}"
    scm_credential: "{{ scm_credential }}"
    scm_update_on_launch: true     # Perform an update to the local repository before launching a job with this project.
    scm_update_cache_timeout: 60
    state: present
    #controller_config_file: "~/tower_cli.cfg"