---
# Define an execution environment that will be used for all subsequent runs
# REF : https://docs.ansible.com/ansible/latest/collections/awx/awx/execution_environment_module.html
# Having  commmon exec environment to be used across all the jobs gives me full control and predictability.

# Default exec env in projects or upstream organization is used as a fallback when an execution environment 
# has not been explicitly assigned at the job template or workflow level.

- name: "Add {{ aap_exec_env_name }} to the aap"
  ansible.controller.execution_environment:
    name: "{{ aap_exec_env_name }}"
    image: "{{ aap_exec_env_image }}"
    description: "{{ aap_exec_env_build_repo }}"
    credential: "{{ container_registry_credential_name }}"
    validate_certs: false 
    state: "present"
    # organization: left blank so that it becomes Globally available.
    pull:  "always" # Incase image is updated at source, to get the latest updates