---
# Re-usable module.
# To add job templates? :
# 1) define them in the group_vars/job-templates-vars.yml
# 2) Feed the variables as set_facts

- name: Create job templates
  ansible.controller.job_template:
    name: "job-{{ name }}"
    job_type: "run"
    description: "{{ aap_objects_build_repo }}"
    organization: "{{ organization }}"
    inventory: "{{ inventory }}"
    project: "{{ project }}"
    playbook: "{{ playbook }}"
    credentials: "{{ credential }}"
    state: "present"
    execution_environment: "{{ aap_exec_env_name }}"
    timeout: 60

# Possible errors
# failed: [localhost] (item=pre-change-checks) => {"ansible_loop_var": "item", "changed": false, "item": "pre-change-checks", "msg": "Unable to update job_template job-pre-change-checks, see response", "response": {"json": {"playbook": ["Playbook not found for project."]}, "status_code": 400}}
# failed: [localhost] (item=config-backup) => {"ansible_loop_var": "item", "changed": false, "item": "config-backup", "msg": "Unable to create job_template job-config-backup: {'playbook': ['Playbook not found for project.']}"}
# Solution : Project might need sync..Go to the AAP GUI and Sync the project again