---
# Creating a list of hosts that is to be used in the lab environment.
# With a smart inventory, this will not be needed.

- name: Adding hosts
  ansible.controller.host:
    name: "{{ item }}"
    description: "{{ aap_objects_build_repo }}"
    inventory: "{{ linux_inventory_name }}"
    state: present
    enabled: true
  loop: 
    - "{{ linux_lab_device_1 }}"
    - "{{ linux_lab_device_2 }}"